version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ALIYA-container
    environment:
      POSTGRES_PASSWORD: dist_pass_123
      POSTGRES_USER: dist_user
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"