version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ALIYA-container
    network_mode: bridge
    networks: 
    - app_net
    environment:
      POSTGRES_PASSWORD: dist_pass_123
      POSTGRES_USER: dist_user
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - ./new.sql:/docker-entrypoint-initdb.d/new.sql

networks:
 app_net: