CREATE TABLE ASYNC_MESSAGES (
  RECORD_ID serial PRIMARY KEY,
  SENDER_NAME varchar(30),
  MESSAGE varchar(30),
  SENT_TIME TIMESTAMP,
  RECEIVED_TIME TIMESTAMP
);

GRANT SELECT, INSERT, UPDATE ON TABLE ASYNC_MESSAGES TO dist_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO dist_user;
